name: Continous Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 22.2.0
        uses: actions/setup-node@v2
        with:
          node-version: "22.2.0"

      - name: Install PM2 globally
        run: npm install -g pm2

      - name: Create .env file
        run: echo "${{secrets.CLIENT_ENV}}" > .env

      - name: Install dependencies and build
        run: npm ci

      - name: Start application
        run: pm2 restart site || pm2 start npm --name "site" -- run start
